package com.countwearables.app.data.model

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Data class representing a clothing item in the user's inventory.
 * Each item is associated with a user through the userId foreign key.
 *
 * @property id Unique identifier for the clothing item (auto-generated by SQLite)
 * @property userId Foreign key referencing the user who owns this item
 * @property name Name of the clothing item (e.g., "T-shirt", "Hoodie")
 * @property category Category of the item (Topwear, Bottomwear, Outerwear, etc.)
 * @property quantity Number of this item owned
 * @property color Color of the item
 * @property size Size of the item (XS, S, M, L, XL, etc.)
 * @property notes Additional notes or description
 * @property imagePath Path to the image file stored on device
 * @property dateAdded Date when the item was added to inventory
 */
data class ClothingItem(
    val id: Long = 0L,  // 0 means new item, will be assigned by database
    val userId: Long,
    val name: String = "",
    val category: String = "",
    val quantity: Int = 1,
    val color: String = "",
    val size: String = "",
    val notes: String = "",
    val imagePath: String = "",
    val dateAdded: Long = System.currentTimeMillis()
) {
    /**
     * Formats the dateAdded timestamp into a human-readable string.
     * @return Formatted date string (e.g., "Jan 1, 2024")
     */
    fun getFormattedDate(): String {
        val sdf = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())
        return sdf.format(Date(dateAdded))
    }
    
    /**
     * Validates if the clothing item has all required fields filled.
     * @return true if name, category, and quantity are valid
     */
    fun isValid(): Boolean {
        return name.isNotBlank() && 
               category.isNotBlank() && 
               quantity > 0
    }
    
    /**
     * Creates a copy of this item with an updated quantity.
     * @param newQuantity The new quantity value
     * @return A new ClothingItem with the updated quantity
     */
    fun withQuantity(newQuantity: Int): ClothingItem {
        return copy(quantity = newQuantity)
    }
    
    /**
     * Creates a copy of this item with an updated image path.
     * @param newPath The new image path
     * @return A new ClothingItem with the updated image path
     */
    fun withImage(newPath: String): ClothingItem {
        return copy(imagePath = newPath)
    }
    
    companion object {
        // Default categories for the app
        val DEFAULT_CATEGORIES = listOf(
            "Topwear",
            "Bottomwear", 
            "Outerwear",
            "Footwear",
            "Accessories",
            "Underwear",
            "Sportswear",
            "Formal Wear",
            "Other"
        )
        
        // Default sizes for the app
        val DEFAULT_SIZES = listOf(
            "XS", "S", "M", "L", "XL", "XXL", "XXXL", "One Size", "Other"
        )
    }
}