package com.countwearables.app.data.model

/**
 * Data class representing a user in the system.
 * This model is used for authentication and to associate clothing items with users.
 *
 * @property id Unique identifier for the user (auto-generated by SQLite)
 * @property username User's username for authentication
 * @property password User's password (stored in plain text for simplicity - 
 *                    in production, use hashing)
 */
data class User(
    val id: Long = 0L,  // 0 means new user, will be assigned by database
    val username: String,
    val password: String
) {
    /**
     * Validates if the user data is valid for registration/login.
     * @return true if username and password are not empty
     */
    fun isValid(): Boolean {
        return username.isNotBlank() && password.isNotBlank()
    }
    
    /**
     * Validates if the user data is valid for registration.
     * @param confirmPassword The password confirmation to check against
     * @return true if all fields are valid and passwords match
     */
    fun isValidForRegistration(confirmPassword: String): Boolean {
        return username.isNotBlank() && 
               password.length >= 6 && 
               password == confirmPassword
    }
}