package com.countwearables.app.data.model

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Data class representing a user in the system.
 * This model is used for authentication and to associate clothing items with users.
 *
 * @property id Unique identifier for the user (auto-generated by SQLite)
 * @property username User's username for authentication
 * @property password User's password (stored in plain text for simplicity - 
 *                    in production, use hashing)
 * @property createdAt Timestamp when the user account was created
 */
@Entity(
    tableName = "users",
    indices = [Index(value = ["username"], unique = true)]
)
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val username: String,
    val password: String,
    val createdAt: Long = System.currentTimeMillis()
) {
    /**
     * Validates if the user data is valid for registration/login.
     * @return true if username and password are not empty
     */
    fun isValid(): Boolean {
        return username.isNotBlank() && password.isNotBlank()
    }
    
    /**
     * Validates if the user data is valid for registration.
     * @param confirmPassword The password confirmation to check against
     * @return true if all fields are valid and passwords match
     */
    fun isValidForRegistration(confirmPassword: String): Boolean {
        return username.isNotBlank() && 
               password.length >= 6 && 
               password == confirmPassword
    }
}